project:
  type: website
  output-dir: docs

website:
  title: HSMA
  site-url: https://www.hsma.co.uk
  description: "The website of the HSMA Programme"
  favicon: resources/favicon.png
  google-analytics:
    tracking-id: "G-9D93EVJKF5"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  announcement:
    icon: megaphone
    dismissable: false
    content: "**Round 6 of HSMA is now complete! We hope to launch HSMA 7 in mid 2026. Want to hear when we open up applications? Send us an email at [penchord@exeter.ac.uk](mailto:penchord@exeter.ac.uk?subject=Contact%20from%20HSMA%20Website%20&body=If%20you%20would%20like%20to%20be%20added%20to%20the%20HSMA%20mailing%20list%2C%20please%20complete%20the%20fields%20below.%0A%0AFull%20Name%3A%0A%0AOrganisation%3A%0A%0AIf%20you%20have%20a%20different%20query%2C%20please%20replace%20the%20content%20of%20this%20message%20with%20your%20own.%20%0A%0AThis%20is%20an%20automatically%20generated%20email%20from%20a%20link%20on%20the%20HSMA%20website) stating your full name and organisation to be added to our mailing list.**"
    type: info
    position: below-navbar
  page-footer:
    center: |
      [![](/resources/nihr_logo.png){width=250px}](https://arc-swp.nihr.ac.uk/)<br/><br/>
      *This report is independent research supported by the National Institute for Health and Care Research Applied Research Collaboration South West Peninsula.
      The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health and Care Research
      or the Department of Health and Social Care.*
      <br/><br/>
      [Accessibility Statement](/policies_procedures/accessibility_statement.qmd)
      <br/>
      [Code of Conduct](/policies_procedures/code_of_conduct.qmd)
      <br/>
      [Concerns and Complaints](/policies_procedures/concerns_and_complaints.qmd)
  navbar:
    logo: "/resources/Chalky HSMA-07-wide white logo.png"
    title: false
    collapse-below: "xl"
    tools:
      - icon: youtube
        href: https://www.youtube.com/@hsma
      - icon: github
        menu:
          - text: View the HSMA Github
            href:  https://github.com/hsma-programme
          - text: View the code for this website
            href:  https://github.com/hsma-programme/hsma_site
      - icon: envelope
        href: mailto:penchord@exeter.ac.uk?subject=Contact%20from%20HSMA%20Website%20&body=If%20you%20would%20like%20to%20be%20added%20to%20the%20HSMA%20mailing%20list%2C%20please%20complete%20the%20fields%20below.%0A%0AFull%20Name%3A%0A%0AOrganisation%3A%0A%0AIf%20you%20have%20a%20different%20query%2C%20please%20replace%20the%20content%20of%20this%20message%20with%20your%20own.%20%0A%0A\*\*This%20is%20an%20automatically%20generated%20email%20from%20a%20link%20on%20the%20HSMA%20website\*\*
      - icon: linkedin
        href: https://www.linkedin.com/company/hsma-programme/
      - icon: rss
        href: news/rss.xml
    right:
      - href: index.qmd
        text: Welcome

      - href: hsma_content/books/books.qmd
        text: Books

      - href: hsma_content/modules/modules.qmd
        text: Modules

      - text: "Projects"
        menu:
          - href: previous_projects/projects_by_service_area.qmd
            text: Projects by Area of Care
          - href: previous_projects/projects_by_service_type_location.qmd
            text: Projects by Care Delivery Location
          - href: previous_projects/projects_by_organisation.qmd
            text: Projects by Organisation
          - href: previous_projects/projects_by_methods.qmd
            text: Projects by Method
          - href: previous_projects/projects_by_cohort.qmd
            text: Projects by HSMA Cohort
          - href: previous_projects/projects_with_code.qmd
            text: Projects With Code Shared
          - href: previous_projects/projects_in_progress.qmd
            text: Projects In Progress
          - href: previous_projects/completed_projects.qmd
            text: Completed Projects

      - href: impact_stories.qmd
        text: Case Studies

      - text: "Student Resources"
        menu:
          - href: project_log_recording_app.qmd
            text: Project Log Recording App
          - href: assessment_faqs.qmd
            text: Assessment Details
          - href: phase_2_details.qmd
            text: Phase 2 Dates & Events
          - href: registering_a_project.qmd
            text: Registering a Project
          - href: project_faqs.qmd
            text: Project FAQs

      - text: "Other Resources"
        menu:
          - href: hsma_content/des_playground.qmd
            text: The DES Playground
          - href: hsma_content/reinforcement_learning_game.qmd
            text: Reinforcement Learning Game

      - href: news.qmd
        text: News

      - text: "About"
        menu:
          - href: about-hsma.qmd
            text: The HSMA Programme
          - href: foss.qmd
            text: HSMA & Open Source Software
          - href: faqs.qmd
            text: Frequently Asked Questions


format:
  html:
    theme:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
    css: styles.css
    toc: true
    title-block-banner: /resources/banner.png
    mainfont: Lexend
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
