project:
  type: website
  output-dir: docs

website:
  title: "HSMA Website"
  # google-analytics:
  #   tracking-id: "G-MBWDD0MCCS"
  #   anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Past HSMA Projects"
        menu:
          - href: previous_projects/index.qmd
            text: Projects by Cohort
          - href: previous_projects/projects_by_methods.qmd
            text: Projects by Method
          - href: previous_projects/projects_by_organisation.qmd
            text: Projects by Organisation
          - href: previous_projects/projects_by_service_area.qmd
            text: Projects by Service Area

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
