project:
  type: website
  output-dir: docs

website:
  title: HSMA
  google-analytics:
    tracking-id: "G-9D93EVJKF5"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  page-footer:
    center: |
      [![](/resources/nihr_logo.png){width=250px}](https://arc-swp.nihr.ac.uk/)<br/><br/>
      *This report is independent research supported by the National Institute for Health and Care Research Applied Research Collaboration South West Peninsula.
      The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health and Care Research
      or the Department of Health and Social Care.*
  navbar:
    logo: /resources/hsma_logo_transparent_background_wide_black.png
    title: false
    tools:
      - icon: youtube
        href: https://www.youtube.com/@hsma
      - icon: github
        menu:
          - text: View the HSMA Github
            href:  https://github.com/hsma-programme
          - text: View the code for this website
            href:  https://github.com/hsma-programme/hsma_site
      - icon: envelope
        href: mailto:penchord@exeter.ac.uk?subject=Contact%20from%20HSMA%20website
    left:
      - href: index.qmd
        text: Welcome
      - text: "HSMA Projects"
        menu:
          - href: previous_projects/projects_by_service_area.qmd
            text: Projects by Service Area
          - href: previous_projects/projects_by_organisation.qmd
            text: Projects by Organisation Type
          - href: previous_projects/projects_by_methods.qmd
            text: Projects by Method
          - href: previous_projects/projects_by_cohort.qmd
            text: Projects by Cohort
      - text: "HSMA Content"
        menu:
          - href: hsma_content/books/books.qmd
            text: HSMA Books
          - href: hsma_content/modules/modules.qmd
            text: HSMA Modules


format:
  html:
    theme:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
    css: styles.css
    toc: true
    title-block-banner: /resources/banner.png
    mainfont: Lexend
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
