project:
  type: website
  output-dir: docs

website:
  title: HSMA
  # google-analytics:
  #   tracking-id: "G-MBWDD0MCCS"
  #   anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  page-footer: 
    left: |
      ![](/resources/nihr_logo.png){width=250px}
    center: |
      *This report is independent research supported by the National Institute for Health and Care Research Applied Research Collaboration South West Peninsula.
      The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health and Care Research
      or the Department of Health and Social Care.*
  navbar:
    logo: /resources/hsma_logo_transparent_background_wide_black.png
    title: false
    left:
      - href: index.qmd
        text: Welcome
      - text: "Past HSMA Projects"
        menu:
          - href: previous_projects/projects_by_service_area.qmd
            text: Projects by Service Area
          - href: previous_projects/projects_by_organisation.qmd
            text: Projects by Organisation Type
          - href: previous_projects/projects_by_methods.qmd
            text: Projects by Method
          - href: previous_projects/projects_by_cohort.qmd
            text: Projects by Cohort


format:
  html:
    theme:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
    css: styles.css
    toc: true
    title-block-banner: https://raw.githubusercontent.com/hsma-programme/hsma_site/refs/heads/main/resources/banner.png
    mainfont: Lexend
