project:
  type: website
  output-dir: docs

website:
  title: "HSMA Website"
  # google-analytics:
  #   tracking-id: "G-MBWDD0MCCS"
  #   anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  body-footer: |
    <br/><br/>![](/resources/nihr_logo.png)<br/><br/>
    *This report is independent research supported by the National Institute for Health and Care Research Applied Research Collaboration South West Peninsula.
    The views expressed in this publication are those of the author(s) and not necessarily those of the National Institute for Health and Care Research
    or the Department of Health and Social Care.*
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Past HSMA Projects"
        menu:
          - href: previous_projects/projects_by_methods.qmd
            text: Projects by Method
          - href: previous_projects/projects_by_service_area.qmd
            text: Projects by Service Area
          - href: previous_projects/index.qmd
            text: Projects by Cohort
          - href: previous_projects/projects_by_organisation.qmd
            text: Projects by Organisation

format:
  html:
    theme:
      - darkly
      - theme-dark.scss
      - resources/fonts/css/lexend.css
    # css: styles.css
    toc: true
    mainfont: Lexend
