---
title: HSMA Certification Guidance
title-block-banner: resources/banner.png
include-back-link: false
---

The HSMA Programme is accredited by the Association of Professional Healthcare Analysts (AphA) and all participants are able to cite this as part of their participation.  However, we also recognise that some participants may want to receive a digital certificate to confirm their completion of the programme.  To this end, we provide optional certification via Accredible.

To ensure that we are only certifying those that have adequately engaged with the course, if a participant would like to be certified, we require some evidence that a participant has both

a) undertaken and sufficiently engaged with the training provided as part of the programme, and
b) is able to apply at least some of the skills taught.

For participants in HSMA 6, we have provided two options for those who wish to receive a certificate.

:::{.callout-tip appearance="simple"}
Participants may either

- Provide their HSMA project work as evidence
*or*
- Undertake the HSMA 6 Assessment
:::

 It should be noted that participants only need to choose ONE of these options if they want certification, and there is no difference in certification between the two options.  Participants can only be certified once.

:::{.callout-note appearance="simple"}
It is also important to note that the certification does not represent a formal academic award, simply a ‘stamp’ of completion of the HSMA programme.
:::

## Option 1: Provide their HSMA project work as evidence

Students may choose to provide their HSMA project work as evidence of their engagement and ability to apply the skills taught.

:::{.callout-tip appearance="simple"}

This is the recommended option for most participants, as it provides us with a more accurate picture of a participant’s ability to use the skills taught in practice over time, and does not require the participant to undertake a separate piece of work under examination conditions.

:::

To submit project work as certification evidence, the following guidelines must be met :

1. The project must be an officially registered HSMA project (registered on the HSMA Project Register).
    - This ensures that the project is one that uses the skills taught on the programme, and has an application area in health, social care or policing

2. The evidence must be submitted as a link to a GitHub repository which contains the code, commit histories and relevant documentation for the project.
    - This should be done either at the end of Phase 2, or may be submitted sooner if the project completes before this time.
    - Submissions after the end of Phase 2 are also permitted, though it should be noted that **the project does not need to be fully complete at the time of submission** as long as there is sufficient evidence of the application of skills present.

:::{.callout-note appearance="simple"}
While most HSMA projects will be code-based, some projects may instead use QGIS or InsightMaker.

We would recommend that these projects still make use of GitHub, and discussions should be had with the programme staff if it is not going to be possible to make use of GitHub.

- Projects using InsightMaker can export the .InsightMaker file and track changes to this on Github.
- QGIS project files can also be uploaded to a GitHub repository. It is recommended that students install the [qgis_trackable_project_files](https://github.com/opengisch/qgis_trackable_project_files) and use the .qgs format.
:::

3. Authorship of code and other materials should be made clear.
    - This is particularly important for projects involving multiple HSMAs, so that each HSMA involved can provide a case for their certification.

4. HSMA Programme staff will look over the work provided.
    - They will determine whether the work demonstrates that the author(s) have sufficiently understood the techniques adopted, and have produced good quality code.
        - If so, certification will be provided.
        - If not, staff will contact the HSMA(s) involved in the first instance to explore
            i. if there is further evidence that they can provide, or
            ii. advise them to resubmit at a later stage when the project has advanced further, or
            iii. if neither of these are possible, to direct them to undertake a subsequent assessment if they still wish to be certified.

:::{.callout-warning appearance="simple"}
The decision of programme staff is final, but extensive discussion will take place for any proposed rejections of evidence before any such decision is taken to ensure that the decision is fair.
:::

## Option 2: Undertake the HSMA 6 Assessment

**If participants are not undertaking a HSMA project, or would prefer to receive certification sooner, they can choose to undertake the HSMA 6 Assessment**


:::{.callout-tip appearance="simple"}
The assessment will take place on 28th January 2025 at 1000 - 1200.

Students should join this session using the normal HSMA Zoom Link.
:::

-  Participants who wish to undertake the assessment must undertake the assessment live unless there are extenuating circumstances (which must be discussed with the programme staff ahead of time).  Participants will have 90 minutes from the start of the assessment to submit their solutions.  Instructions for how to do this, and how the assessment will be released, will be provided in an introductory 30 minute session on the day.

- HSMAs can choose to undertake an assessment for a future round should they fail or not choose or be able to take the HSMA 6 assessment.  Details of future assessments will be shared with the community on Slack.  However, we cannot at any point ‘guarantee’ future rounds (and therefore future assessments) as the HSMA programme is dependent on fixed term funding.

- Participants are required to have a working, local installation of Python, along with the ability to work with Jupyter Notebooks, to undertake the assessment.  Some questions will benefit from the HSMA having access to prior environments set up during the training phase to test solutions, though code can still be written and submitted without this.

- The assessment is “open book” - therefore, HSMAs are welcome to refer to any notes they choose to help them answer the questions.  However, plagiarism is strictly prohibited, and this includes using an AI tool to write the code for you.  HSMA programme staff and others HSMAs also cannot be used to ask for help during the assessment.

- The assessment consists of three “core” questions which test basic Python skills, and a series of additional questions, from which HSMAs should choose any two to answer.  These additional questions are based on the various modelling and data science approaches taught in Phase 1.

- The assessment is supplied as a Jupyter Notebook.  Each question in the assessment asks the HSMA to write some code in the corresponding code cell to achieve a task.  Typically, some code will already be present in the code cell, and the HSMA must simply add code to the cell where indicated.

- Each question is worth a set number of marks (with all non-core questions awarding equal marks).  If the code written by the HSMA works and does what is asked, then full marks for the question are awarded.  If not, marks are awarded at the marker’s discretion depending on how close to a working solution they were.  The HSMA Programme staff will mark the assessments.

- To pass the assessment and receive certification, a HSMA must achieve at least 50% of the available marks.  There is no distinction in certification for marks awarded above this.

- The decision of the markers is final.  However, all potential “fail” cases will be moderated by both markers to ensure that the decision is fair and consistent with other marks awarded.  All marked submissions will be returned to participants so they can see how they scored.
