# FAQs

## What Techniques Can I Base a Project Around?
 Projects have generally had a focus on one of these techniques:
- Discrete Event Simulation
- Mapping (often, but not always, involving calculation of travel times)
- Location Optimization (Finding optimal combinations of sites)
- Machine Learning (Classification or Regression Modelling)
- Natural Language Processing
- Agent-based Simulation

Projects can and do use a mixture of these, too - e.g. bringing in elements of the geographic modelling module in a discrete event simulation.

The additional things that are more likely to just be a part of your project (though sometimes they can be a very significant part depending on the project!) are:
- System Dynamics
- Time-series Forecasting methods (e.g. ARIMA, Prophet)
- Process Mining
- Web Apps
- Automation

We did previously teach network analysis as well, so you may see one or two topics crop up in that area; however, we’ve lost our network analysis expert from our wider team and removed this from the syllabus. For areas like this, or things like machine learning techniques or natural language processing techniques that we don't explictly teach, we can generally still support projects in this area to some extent - we just may be able to provide less in-depth support on the techniques themselves if they're not something we directly teach and have used ourselves, but there may be other people in the community who can help!

## When should I be starting my project?

We generally recommend you begin your projects at the end of Phase 1 (end of October 2024). However, you can now register and begin projects early if you so wish!
Can HSMAs do multiple smaller projects in the inception project phase, or is this discouraged?
HSMAs can do as many or as few as they wish, and we've had HSMAs before that have done this.  This is even easier now, as anyone can start and finish a project at any time they choose.  Sometimes, it can be useful to have something else in your back pocket as you realise how long it's going to take to get the data you need for a project... The only thing I would say to anyone is be cautious about being too ambitious with project ideas or numbers if you only have a day a week on this.  A day a week for 9 months isn't a huge amount of time - you are (generally) much better off carving off something useful and doable that you can build on, rather than trying to start big by trying to do too much.

## What steps do I need to take to get my project up and running?

Once you have an idea of what you want your project to be, please post in the [#new_project_airlock](https://hsma-workspace.slack.com/archives/C074HBCAGGM) Slack channel with a brief description of any project you'd like to register as a HSMA project.

The team will then create you a channel on Slack to use for project discussions, and register your project on the current HSMA project register.

You don't need to do anything more formal than that - you can start cracking on with your code and using the HSMA community for help.

## Do I need to share the data used for the project!

Definitely not!

We recognise that this generally isn’t possible.

When we talk about free and open source for the project, we are interested in
The code being made available
The key outputs and findings being shared in some capacity - even if it’s not possible to share detailed outputs due to the sensitivity

To allow people to try running your project, it can be advisable to provide a sample dataset in your repository. This doesn’t have to match the reality of patterns seen in your organsation.

## If sharing the code/model, do I need to make this generalisable to the entire population or is it ok for it to be specialised towards my organisation?

It’s absolutely fine for it to be very specialised towards your organisation - you may just want to consider giving a warning in your readme.
