# Tips for Generating Project Ideas

If you are struggling to get started with project ideas, here are a couple of prompts to help.

1. Take a look at the [previous HSMA projects](previous_projects/index.qmd) and [non-HSMA projects from across the NHS and academia](non_hsma_projects/index.qmd).

2. Think about the areas of the course you most enjoyed. While the needs of the organisation need to come first, it's also helpful to consider the areas of the course you

- found the most interesting
- felt you broadly understood (don't feel you have to be an expert yet - you will practice and develop your skills significantly over the next 9 months!)
- would like to work with more in the long run in your career/begin to specialise in

This interest will help sustain you through the more difficult moments of the project!

3. Think about any areas you know to be struggling in your organisation at the moment. Are there services you know have particularly long waits? Are there areas people often mention as being a concern? Are there articles in the wider news about waits in a particular service in your organisation?

4. Think about the questions you have found yourself being asked in the past in your role that you didn't feel you were able to answer. Have people asked you questions about the ideal staffing levels, the future demand, or where the delays in a pathway are?

5. Think about the stakeholders you have good relationships with. Could you reach out to them to have a chat about areas they may be interested in someone doing a deeper dive into?

6. Talk to your manager - they may have more awareness of the key challenges facing the organisation at present.


## Tips for scoping a good project

- You ideally want projects that are not too time-critical to the organisation; remember that you may be working on this for 9 months (or more!).
    - With that being said, shorter projects - or projects that you work on more intensely than 1 day a week so that they are completed in a shorter space of time - are fine too!  

- Start small and focussed; you can always expand the scope of the project down the line, but consider limiting your initial project to a single service or even sub-service.
    - Don't worry that your project is 'too simple'! Nothing is ever quite as simple as it seems, and 'simple' modelling can still be highly impactful. 

- Consider the possible ethical issues with your project early on.
    - This can be particularly tricky with machine learning projects. Refer back to the AI module - does it run into murky territory?
    - Often predictions that are aggregated in some way are a safer option than those that are used to directly influence a patient's care. For example, predicting the number of patients who are likely to be admitted to each specialty in the next 6 hours can help with optimizing bed management - but using that prediction for an individual patient to alter their pathway or care is likely to not be ok.

- Consider the data requirements for your proposed project. Do you need data that you know is already collected in some capacity, or would you need to collect brand new data?
    - Is it a dataset you already have access to? If not, consider how you may be able to progress elements of the project while waiting for access to be granted. This part can often take longer than you expect.

- Consider the impact
    - What information can you give people at the end of your project, and what will they be able to do with it?