---
title: Phase 2 Dates and Events
title-block-banner: resources/banner.png
include-back-link: false
---


During phase 2 of HSMA 6, which runs until Wednesday 25th June 2025, students are expected to be working on their inception project the equivalent of one day a week. A range of events are also scheduled to take place during this time.

## Forums

Forums are a space for everyone working on projects to come together, share updates on their projects and, perhaps most importantly of all, to share ideas with each other.

:::{.callout-tip appearance="simple"}
Attendance is expected at forums for anyone who is involved in a project.

For those who have not yet registered a project, forum attendance is still highly recommended.
:::

Forums will contain several short demonstrations and talks from students who are currently working on their projects, as well as presentations from programme staff on additional useful tools and techniques.

7 forums are scheduled to take place during phase 2 of the programme - one per month.

Forums run from 10am to 12pm.

1. Tuesday 19th November 2024
2. Tuesday 10th December 2024
3. Tuesday 21st January 2025
4. Tuesday 18th Feburary 2025
5. Tuesday 18th March 2025
6. Tuesday 29th April 2025
7. Tuesday 27th May 2025

:::{.callout-note appearance="simple"}
Note that the joining link for these sessions is the same as all other HSMA sessions.
:::

## HSMA Conference

At the end of the HSMA round, there will be a HSMA Conference.  This will be an opportunity for those in the HSMA community to come together to present their work.

Invites will also be open to audience members more widely in health, social care and policing practice and academia, including those interested in applying.

Most of the talks at the conference will be Inception Projects but there will also be :

- Talks from HSMA alumni about further projects / work they have undertaken
- Workshops
- Talks from the PenCHORD team about their research

:::{.callout-tip appearance="simple"}
The conference for HSMA 6 will take place on
Tuesday 24th June 2025.
:::
