---
title: Project Registration Process
---

Once you have an idea of what you want your project to be, please post in the [#new_project_airlock](https://hsma-workspace.slack.com/archives/C074HBCAGGM) Slack channel with a brief description of any project you'd like to register as a HSMA project.

The team will then create you a channel on Slack to use for project discussions, and register your project on the current HSMA project register.

You don't need to do anything more formal than that - you can start cracking on with your project work and use your project channel to reach out to the HSMA community for help.

:::{.callout-note}
While we provide a [project design template](https://bergam0t.github.io/hsma_project_handbook/project_design_template.html), this is **entirely optional** and is only designed to guide your thinking. If you have filled it out, it is helpful for us if you submit it along with your brief project description in the [#new_project_airlock](https://hsma-workspace.slack.com/archives/C074HBCAGGM) - but you do not have to fill in every field, or even fill it in at all if you don't find it helpful!!
:::

## Examples
Here's are some example registration messages. More detailed messages are welcomed and help us to get the best idea of your project, but a couple of sentences outlining the rough question and method is fine too, and is sufficient in many cases!

---

**Example 1**

Can I register a project using DES to model patient navigation of GP vs 111 and the knock-on effect on ED please?

---

**Example 2**

My project:

Name: Use DES to optimise theatre capacity for elective procedures and major trauma arrivals in Orthopaedics

Background: Orthopaedic Trauma – Emergency Referrals (Major Trauma) increasing over the last 4-5 months; UHCW is a Major Trauma Centre so receive patients from further afield as well as local patients. Also, a Tertiary referral centre for specialised surgeries. This is impacting on elective lists as not enough capacity to do alongside emergency cases. Having a financial impact on the Trust due to money Orthopaedics brings in but activity is unable to happen due to emergency cases, waiting lists increasing. Harder to get patients back from elsewhere due to lack of resource/capacity.

Aim: To create a DES model showing the major trauma and elective surgery pathways in Orthopaedics and experiment with adding extra theatre slots and/or increasing capacity elsewhere in the pathway to improve flow and the waiting list.

Proposed outputs:
Initial analysis of demand, patient type, IP/OP LOS/capacity
Interactive DES Model to adjust various capacity metrics (e.g. number of sessions, slots, resource capacity).
I may also do a bit of geographical modelling to see where the trauma and tertiary patients are coming from.
Forecasting to spot trends in time of day, seasonality, day of week in major trauma arrivals

## Additional Information

:::{.callout-note}
HSMA projects must meet a few criteria

- They must use a method we teach on the HSMA course
    - the method can be related to a method we teach - for example, if you wished to use a time series forecasting method we haven't taught, this would be ok, but we may be able to provide less detailed support than for a technique we have taught
- It must use free and open source methods
- It must be in the area of health, social care, policing,
:::


:::{.callout-tip}
Take a look at the [FAQs](faqs.qmd) if you have any questions.
:::
