---
title: "Developing a Service Planning Decision Support Tool to Tackle Inequalities and Minimise Carbon Output"
categories:
  - Non-attendance Prediction
  - Machine Learning
  - Automation
  - Inequalities
  - Carbon Emissions
  - Health Equity Audits
  - NHS
techniques:
  - Machine Learning
  - Automation
author:
  - name: Matt Eves
    affiliation: Derbyshire Community Health Services NHS
  - name: Anya Gopfert
    affiliation: Torbay Council
  - name: Sally Brown
    affiliation: West Sussex County Council
organisations:
  - Derbyshire Community Health Services NHS
  - Torbay Council
  - West Sussex County Council
image: "bef68gj9.bmp"
title-block-banner: ../../banner.png
pub-info:
  links:
  - name: Video
    url: https://www.youtube.com/watch?v=zYWte2obxDs&list=PLgHO2TgIJXdn0k4y56xtM-VpcHU_5RJUN&index=8
    icon: fa-brands fa-youtube
  - name: Code
    url: https://github.com/hsma4-student/shine
    icon: fa-brands fa-github
---

There are three current significant health agendas to which this project broadly relates.

These are

1. The inequalities agenda
2. The digital and transformation agenda, and
3. The Net Zero agenda.

The aim of this project was to explore feasibility of considering the impact of a new clinic location on inequalities and carbon emissions, and any co-benefits or trade-offs between the two. Ultimately, the aim was to enable decision making to incorporate these two significant areas.

The team have achieved:

1. The automation of a Health Equity Assessment to compare the profile of patients in a service to the population at large

2. The running of a number of variations to a logistic regression model to identify features predictive of someone not attending their appointment

3. Quantifying an estimate for the patient travel carbon emissions associated with the current service design.

They are intending to continue working together as a team to finish the project’s initial scope (e.g. inc. possible new clinic sites and model impact on unmet need / emissions) – potentially supported by code from another project, emphasising the benefit of open source.

They have been successful in securing a funding from the Greener NHS Healthier Futures Action Fund joint bid.

{{< video https://www.youtube.com/watch?v=zYWte2obxDs&list=PLgHO2TgIJXdn0k4y56xtM-VpcHU_5RJUN&index=8 >}}


```{=html}
<iframe width="780" height="500" src="https://github.com/hsma4-student/shine" title="Code"></iframe>
```
