---
title: Code of Conduct
date: October 2023
title-block-banner: ../resources/banner.png
---

Health Service Modelling Associates (HSMA) Programme Code of Conduct

Welcome to the HSMA Programme. This course is designed to help you learn new skills and knowledge in an engaging and interactive way. You will frequently be interacting with other learners, trainers, and mentors through various online platforms, such as live lectures, discussions and group exercises over Zoom, discussions and chats via Slack, and the HSMA YouTube channel.

As a member of this online learning community, you are expected to follow some basic rules of good online behaviour, also known as netiquette. These rules are intended to create a positive, respectful, and inclusive learning environment for everyone. By enrolling in this course, you agree to abide by this code of conduct.

Everyone in the HSMA community is expected to :

- Be polite and courteous. Use appropriate language and tone when communicating with others. Avoid using profanity, insults, sarcasm, or personal attacks. Respect the opinions and perspectives of others, even if they differ from your own. Avoid interrupting others when they are speaking, and ensure that everyone has an opportunity to contribute their voice.

- Be constructive and supportive. Provide helpful feedback and encouragement to others. Acknowledge the contributions and achievements of others. Appreciate that people learn at different speeds, and support others wherever you can. Avoid spamming, trolling, flaming, or disrupting online discussions.

- Be honest and ethical. Do not plagiarize, cheat, or falsify information. Do not share your login credentials or personal information with others. Do not misuse or abuse the online resources or platforms provided by the course.

- Be responsible and respectful. Follow the instructions and guidelines provided by the trainers and other programme staff. Undertake tasks and group exercises to the best of your ability. Contribute to group exercises, and allow and support others to contribute. Respect the privacy and confidentiality of others. Do not post or share any inappropriate, offensive, or illegal content or material.

- Be open-minded and curious. Explore new ideas and perspectives. Ask questions and seek clarification when needed. Learn from your mistakes and feedback. Challenge yourself and others to grow and improve.

If you encounter any issues or problems with the course content, platforms, or participants, please follow the Concerns and Complaints procedure.

Any violation of this code of conduct may result in disciplinary actions, such as warnings, removal from the course, or reporting to the authorities where illegal activity has been exposed. The course provider (NIHR PenARC) reserves the right to modify or update this code of conduct at any time without prior notice.

We hope that you enjoy the HSMA Programme and being part of the HSMA community.
