---
title: Concerns and Complaints
title-block-banner: ../resources/banner.png
---

We hope that participants' experience on HSMA is not only informative and educational, but also fun and enjoyable.  We endeavour to provide a safe, happy and inclusive learning environment for all of our participants.  However, should any participant have any concerns or complaints about any aspect of the programme, they should either :

a) contact the HSMA Programme Lead (Dr Daniel Chalk) in the first instance, either via direct message on the HSMA Slack Workspace, or via email ([d.chalk@exeter.ac.uk](mailto:d.chalk@exeter.ac.uk))

b) if it is not appropriate to contact the Programme Lead (because the complaint / concern involves the Programme Lead, or because the participant would feel more comfortable speaking to someone else), the participant should contact one of the other programme staff.

c) if it is not appropriate to speak to any of the programme staff, the participant can raise their concern directly with the PenCHORD Management Team by emailing [penchord@exeter.ac.uk](mailto:penchord@exeter.ac.uk).

Any concerns raised will be investigated and a full response issued.  If the participant is unhappy with the response, the matter will be referred to the management team for investigation.
