---
title: "Developing a generic vaccination service model for the COVID-19 pandemic and beyond"
categories:
  - Discrete Event Simulation
  - Vaccination
  - COVID-19
  - NHS
author:
  - name: Dr Adam Kwiatkowski
    affiliation: GP and Clinical Director, Torridge Primary Care Network
image: "wjcl716l.bmp"
title-block-banner: ../../banner.png
organisations:
  - Torridge Primary Care Network
pub-info:
  links:
  - name: Video
    url: https://www.youtube.com/watch?v=Ve5LuePWrQ4&list=PLgHO2TgIJXdnAWY7tGGPQLWYAjn0tgG_A&index=3
    icon: fa-brands fa-youtube
  - name: Code
    url: https://colab.research.google.com/drive/1d7AFLHy6XWvz-_l6MPb2U2bOew6lwk5f?invite=CM3zt9AG
    icon: fa-brands fa-github
---

In winter 2020, vaccinations had recently been approved for use in the UK to protect people against the COVID-19 virus. Consequently, a mass vaccination programme was required to vaccinate most of the population of the country, which led to local GP surgeries having to pivot to deliver vaccinations for their communities at a scale and pace never seen before.

This project was led by a HSMA who had never undertaken any coding work before but using his training from the HSMA programme he rapidly developed a Discrete Event Simulation model of the proposed pathway and resourcing for a vaccination service in North Devon. The model was able to predict not only the rate at which patients could be vaccinated with proposed resourcing, but also the potential risks of social distancing breaches in the waiting room and overflowing in the carpark. The model identified potential issues with the proposed plans, and was used to refine the plans to enable a safe but efficient delivery of the vaccinations in North Devon.

The HSMA also worked with the South West Academic Health Science Network (AHSN) to develop a generic version of the model that could be used for any future vaccination services, and has made the model available Free and Open Source for anyone to use anywhere in the world:

Dr Kwiatkowski said:
“I enjoyed designing it. It predicts queue lengths, car park capacity and times for every step of the vaccination process in the clinic to avoid overcrowded waiting rooms. In the winter of 2020/1 the country was back in lock down and there seemed no end in sight regarding COVID. The vaccines seemed like a ray of hope and setting up the clinics was instrumental in turning the tide. Being able to use the knowledge gained from the HSMA course to help design the process was fantastic. The clinic has now delivered over 100,000 vaccines.”

{{< video https://www.youtube.com/watch?v=Ve5LuePWrQ4&list=PLgHO2TgIJXdnAWY7tGGPQLWYAjn0tgG_A&index=3 >}}

```{=html}
<iframe width="780" height="500" src="https://colab.research.google.com/drive/1d7AFLHy6XWvz-_l6MPb2U2bOew6lwk5f?invite=CM3zt9AG" title="Code"></iframe>
```
