---
title: "Projects by Organisation"
toc-location: right
title-block-banner: banner.png
include-back-link: false
grid:
  sidebar-width: 0px
  body-width: 1100px
  margin-width: 300px
  gutter-width: 1.5rem
listing:

    - id: projects_0
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Ashgate Hospice"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_1
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Avon & Somerset Constabulary"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_2
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "BCP Council"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_3
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Barts Health NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_4
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Bedfordshire Police"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_5
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Birmingham & Solihull Mental Health NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_6
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Blackpool Teaching Hospitals NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_7
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Chesterfield Royal Hospital NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_8
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Counter Terrorism Policing"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_9
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Countess of Chester Hospital NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_10
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Dartford and Gravesham NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_11
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Derbyshire Community Health Services NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_12
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Derbyshire Police"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_13
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Devon & Cornwall Police"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_14
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Devon Air Ambulance"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_15
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Devon County Council"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_16
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Devon Partnership NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_17
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Dorset Council"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_18
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Dorset HealthCare University NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_19
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Dorset Intelligence and Insight Service (NHS Dorset)"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_20
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "East Kent Hospitals University NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_21
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Epsom and St Helier University Hospitals NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_22
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Gloucestershire Hospitals NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_23
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Great Western Hospitals NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_24
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Greater Manchester Police"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_25
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Guy’s and St Thomas’ NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_26
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Health Innovation Wessex"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_27
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Homerton Healthcare"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_28
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Imperial College Healthcare NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_29
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "King's College Hospital NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_30
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Lancashire & South Cumbria NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_31
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Lancashire and South Cumbria NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_32
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Liverpool University Hospitals NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_33
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Maidstone and Tunbridge Wells NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_34
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Manchester University NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_35
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS Arden & GEM CSU"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_36
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS Bath and North East Somerset, Swindon and Wiltshire ICB"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_37
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS Blood and Transplant"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_38
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS Devon ICB"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_39
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS Dorset ICB"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_40
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS England"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_41
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS England Specialised Commissioning – South East Region"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_42
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS Midlands and Lancashire CSU"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_43
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS North Central London ICB"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_44
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS North East London CSU"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_45
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS North of England CSU"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_46
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS North of England CSU (NECS)"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_47
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS South West London ICB"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_48
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS South, Central and West CSU"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_49
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NHS West Yorkshire ICB"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_50
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "NIHR Clinical Research Network"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_51
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "National Crime Agency"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_52
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "National Disease Registration Service (NDRS)"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_53
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Norfolk County Council"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_54
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Norfolk and Suffolk NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_55
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "North West Ambulance Service NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_56
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "North West London ICB"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_57
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "North West Neonatal operational Delivery Network (NWNODN)"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_58
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Nottingham University Hospitals NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_59
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Oxford Health NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_60
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Peninsula Dental Social Enterprise"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_61
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Public Health Dorset"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_62
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Reading Borough Council"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_63
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Royal Cornwall Hospitals NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_64
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Royal Devon University Healthcare NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_65
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Royal United Hospitals Bath NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_66
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Sandwell and West Birmingham NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_67
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Sheffield Children's NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_68
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Solent NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_69
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Somerset NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_70
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "South Central Ambulance Service NHS Foundation Trust (SCAS)"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_71
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "South Western Ambulance Service NHS Trust (SWAST)"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_72
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Surrey and Borders Partnership NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_73
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Surrey and Sussex Healthcare NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_74
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "The Park Medical Practice"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_75
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "The Royal College of Pathologists"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_76
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "The Strategy Unit"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_77
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "The Walton Centre NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_78
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Torbay Council"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_79
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Torbay and South Devon NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_80
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Torridge Primary Care Network"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_81
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "UCL Partners Health Innovation"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_82
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "University College London Hospitals NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_83
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "University Hospitals Bristol and Weston NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_84
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "University Hospitals Coventry & Warwickshire NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_85
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "University Hospitals Plymouth NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_86
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "University Hospitals of Morecambe Bay NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_87
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "University of Plymouth"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_88
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Walton Centre NHS Foundation Trust"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_89
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "West Sussex County Council"
      template: ../html/previous_projects/listing.ejs
    
    - id: projects_90
      contents: "*/*/index.qmd"
      sort: "date desc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: false
      include:
        organisations: "Yorkshire Ambulance Service NHS Trust"
      template: ../html/previous_projects/listing.ejs
    
---


```{=html}
<style>
h2 {
text-transform: uppercase;
font-weight: 400;
text-align: left;
}
</style>
```


## Ashgate Hospice


:::{#projects_0}
:::


## Avon & Somerset Constabulary


:::{#projects_1}
:::


## BCP Council


:::{#projects_2}
:::


## Barts Health NHS Trust


:::{#projects_3}
:::


## Bedfordshire Police


:::{#projects_4}
:::


## Birmingham & Solihull Mental Health NHS Foundation Trust


:::{#projects_5}
:::


## Blackpool Teaching Hospitals NHS Foundation Trust


:::{#projects_6}
:::


## Chesterfield Royal Hospital NHS Foundation Trust


:::{#projects_7}
:::


## Counter Terrorism Policing


:::{#projects_8}
:::


## Countess of Chester Hospital NHS Foundation Trust


:::{#projects_9}
:::


## Dartford and Gravesham NHS Trust


:::{#projects_10}
:::


## Derbyshire Community Health Services NHS Foundation Trust


:::{#projects_11}
:::


## Derbyshire Police


:::{#projects_12}
:::


## Devon & Cornwall Police


:::{#projects_13}
:::


## Devon Air Ambulance


:::{#projects_14}
:::


## Devon County Council


:::{#projects_15}
:::


## Devon Partnership NHS Trust


:::{#projects_16}
:::


## Dorset Council


:::{#projects_17}
:::


## Dorset HealthCare University NHS Foundation Trust


:::{#projects_18}
:::


## Dorset Intelligence and Insight Service (NHS Dorset)


:::{#projects_19}
:::


## East Kent Hospitals University NHS Foundation Trust


:::{#projects_20}
:::


## Epsom and St Helier University Hospitals NHS Trust


:::{#projects_21}
:::


## Gloucestershire Hospitals NHS Foundation Trust


:::{#projects_22}
:::


## Great Western Hospitals NHS Foundation Trust


:::{#projects_23}
:::


## Greater Manchester Police


:::{#projects_24}
:::


## Guy’s and St Thomas’ NHS Foundation Trust


:::{#projects_25}
:::


## Health Innovation Wessex


:::{#projects_26}
:::


## Homerton Healthcare


:::{#projects_27}
:::


## Imperial College Healthcare NHS Trust


:::{#projects_28}
:::


## King's College Hospital NHS Foundation Trust


:::{#projects_29}
:::


## Lancashire & South Cumbria NHS Foundation Trust


:::{#projects_30}
:::


## Lancashire and South Cumbria NHS Foundation Trust


:::{#projects_31}
:::


## Liverpool University Hospitals NHS Foundation Trust


:::{#projects_32}
:::


## Maidstone and Tunbridge Wells NHS Trust


:::{#projects_33}
:::


## Manchester University NHS Foundation Trust


:::{#projects_34}
:::


## NHS Arden & GEM CSU


:::{#projects_35}
:::


## NHS Bath and North East Somerset, Swindon and Wiltshire ICB


:::{#projects_36}
:::


## NHS Blood and Transplant


:::{#projects_37}
:::


## NHS Devon ICB


:::{#projects_38}
:::


## NHS Dorset ICB


:::{#projects_39}
:::


## NHS England


:::{#projects_40}
:::


## NHS England Specialised Commissioning – South East Region


:::{#projects_41}
:::


## NHS Midlands and Lancashire CSU


:::{#projects_42}
:::


## NHS North Central London ICB


:::{#projects_43}
:::


## NHS North East London CSU


:::{#projects_44}
:::


## NHS North of England CSU


:::{#projects_45}
:::


## NHS North of England CSU (NECS)


:::{#projects_46}
:::


## NHS South West London ICB


:::{#projects_47}
:::


## NHS South, Central and West CSU


:::{#projects_48}
:::


## NHS West Yorkshire ICB


:::{#projects_49}
:::


## NIHR Clinical Research Network


:::{#projects_50}
:::


## National Crime Agency


:::{#projects_51}
:::


## National Disease Registration Service (NDRS)


:::{#projects_52}
:::


## Norfolk County Council


:::{#projects_53}
:::


## Norfolk and Suffolk NHS Foundation Trust


:::{#projects_54}
:::


## North West Ambulance Service NHS Trust


:::{#projects_55}
:::


## North West London ICB


:::{#projects_56}
:::


## North West Neonatal operational Delivery Network (NWNODN)


:::{#projects_57}
:::


## Nottingham University Hospitals NHS Trust


:::{#projects_58}
:::


## Oxford Health NHS Foundation Trust


:::{#projects_59}
:::


## Peninsula Dental Social Enterprise


:::{#projects_60}
:::


## Public Health Dorset


:::{#projects_61}
:::


## Reading Borough Council


:::{#projects_62}
:::


## Royal Cornwall Hospitals NHS Trust


:::{#projects_63}
:::


## Royal Devon University Healthcare NHS Foundation Trust


:::{#projects_64}
:::


## Royal United Hospitals Bath NHS Foundation Trust


:::{#projects_65}
:::


## Sandwell and West Birmingham NHS Trust


:::{#projects_66}
:::


## Sheffield Children's NHS Foundation Trust


:::{#projects_67}
:::


## Solent NHS Trust


:::{#projects_68}
:::


## Somerset NHS Foundation Trust


:::{#projects_69}
:::


## South Central Ambulance Service NHS Foundation Trust (SCAS)


:::{#projects_70}
:::


## South Western Ambulance Service NHS Trust (SWAST)


:::{#projects_71}
:::


## Surrey and Borders Partnership NHS Foundation Trust


:::{#projects_72}
:::


## Surrey and Sussex Healthcare NHS Trust


:::{#projects_73}
:::


## The Park Medical Practice


:::{#projects_74}
:::


## The Royal College of Pathologists


:::{#projects_75}
:::


## The Strategy Unit


:::{#projects_76}
:::


## The Walton Centre NHS Foundation Trust


:::{#projects_77}
:::


## Torbay Council


:::{#projects_78}
:::


## Torbay and South Devon NHS Foundation Trust


:::{#projects_79}
:::


## Torridge Primary Care Network


:::{#projects_80}
:::


## UCL Partners Health Innovation


:::{#projects_81}
:::


## University College London Hospitals NHS Foundation Trust


:::{#projects_82}
:::


## University Hospitals Bristol and Weston NHS Foundation Trust


:::{#projects_83}
:::


## University Hospitals Coventry & Warwickshire NHS Trust


:::{#projects_84}
:::


## University Hospitals Plymouth NHS Trust


:::{#projects_85}
:::


## University Hospitals of Morecambe Bay NHS Foundation Trust


:::{#projects_86}
:::


## University of Plymouth


:::{#projects_87}
:::


## Walton Centre NHS Foundation Trust


:::{#projects_88}
:::


## West Sussex County Council


:::{#projects_89}
:::


## Yorkshire Ambulance Service NHS Trust


:::{#projects_90}
:::


