---
title: Improving the design and organisation of neonatal care networks – a computer simulation study
categories:
  - Discrete Event Simulation
  - Neonatal care
  - Maternity
  - Staffing Guidelines
  - Cost Analysis
author:
  - name: Dr Alison Harper
    affiliation: PenCHORD/UoE Business School
  - name: Prof Martin Pitt
    affiliation: PenCHORD
  - name: Dr. Richard Wood
    affiliation: PenCHORD
---

> The aim of this project was "To develop a computer model that could mimic the performance of a neonatal network and predict the effect of altering network configuration on neonatal unit workloads, ability to meet nurse staffing guidelines, and distance from the parents’ home location to the point of care... to provide a model to assist in planning of capacity, location and type of neonatal services. "

The model was able to explore the cost of staffing per infant when meeting the guidance 85% and 95% of the time.

They also explored the potential benefits of using wider network staffing capacity to meet peaks of demand more cost-effectively, as well as the "number and distance of transfers, average travel distances for parents, and numbers of parents with an infant over 50 km from home."

<https://pubmed.ncbi.nlm.nih.gov/25996022/>
