---
title: The Discrete Event Simulation Playground
title-block-banner: banner.png
include-back-link: false
page-layout: full
grid:
  sidebar-width: 0px
  body-width: 1400px
  margin-width: 300px
  gutter-width: 1.5rem
toc: false
filters:
  - bergam0t/value-box
---

```{=html}
<style>

body {
	text-align: center;
}

a {
	color: rgb(255, 255, 255);
	text-decoration: underline;
	-webkit-text-decoration: underline;
	-moz-text-decoration: underline;
	-ms-text-decoration: underline;
	-o-text-decoration: underline;
  padding: 2px
}

.custom-button:hover a {
  background-color: white;    /* White background on hover */
  color: #3d3d3d;              /* Grey text on hover */
  border-color: #3498db;      /* Blue border on hover */
}

@media only screen and (max-width: 600px) {

.hsma-iframe {
  height: 350px
}
}

@media only screen and (max-width: 800px) {

.hsma-iframe {
  height: 450px
}
}

@media only screen and (min-width: 800px) {

.hsma-iframe {
  height: 700px
}

}

</style>
```

Discrete Event Simulation is a powerful tool for improving pathways, of which there are a lot in healthcare services.

Originally built for introducing people to Discrete Event Simulation at our open day, this web application is freely available for you to use and adapt.

```{=html}
<div class="project-link-buttons">
    <ul class="project-links">
        <button class="custom-button"><a href="https://hsma-programme.github.io/Teaching_DES_Concepts_Streamlit/"><i class="fa-solid fa-globe"></i><span style="padding-left: 10px;">Open the Playground in a New Tab</span></a></button>
        <button class="custom-button"><a href="https://github.com/hsma-programme/Teaching_DES_Concepts_Streamlit"><i class="fa-brands fa-github"></i><span style="padding-left: 10px;">View the Code</span></a></button>
    </ul>
</div>
```

Try it out below!

<div style="display: flex; justify-content: center; align-items: center;">

::: {.value-box fragment="fade-in" icon="fa-solid fa-lightbulb" icon-position="left" align="center" color="bg-green" font-size="1.3rem" width="50%" min-height="80px"}
Want more of a guided walkthrough?

Keep scrolling!
:::
</div>



```{=html}
<iframe class="hsma-iframe" width="90%" src="https://hsma-programme.github.io/Teaching_DES_Concepts_Streamlit/" title="HSMA DES Playground"></iframe>
```

<br/>

## HACA 2025 Workshop

Want a bit more of a guided walkthrough of the DES playground?

[Lucy Morgan (now Head of Analytics & Modelling at the Strategy Unit)](https://www.strategyunitwm.nhs.uk/author/lucy-morgan) ran two workshops at the Health and Care Analytics (HACA) conference in 2025 that made use of the DES playground.

If you're brand new to simulation, you might first want to watch part 1 - "An introduction to simulation: The tool that will power up your strategic decision making".

{{< video https://www.youtube.com/watch?v=fhqkM1LqXGs width="1000" height="600" >}}

Part 2 - "A simulation deep dive: Get hands on with the inner workings of a simulation model" - then walks you through modelling with a guided tour of the DES playground.

{{< video https://www.youtube.com/watch?v=LpcojxAegl0 width="1000" height="600" >}}
