---
title: "Using Discrete Event Simulation to model the bottlenecks in the Acute Medical Unit pathway"
categories:
  - Discrete Event Simulation
  - Streamlit
  - Acute Medical Unit (AMU)
  - Emergency Departments
  - Acute Care
  - Hospitals
author:
  - name: Becky Crofts
    affiliation: Royal Devon University Healthcare (RDUH) NHS Foundation Trust
  - name: Kayleigh Haydock
    affiliation: Royal Devon University Healthcare (RDUH) NHS Foundation Trust
image: "cd4dqcnc.bmp"
pub-info:
  links:
  - name: Video
    url: https://www.youtube.com/watch?v=_3j0xC_yCKQ
    icon: fa-brands fa-youtube
  - name: Code
    url: https://github.com/BeckyCrofts/amu_modelling
    icon: fa-brands fa-github
---

The team’s project was to create a computer model of part of the acute medical pathway in their hospital trust. As part of this process patients come in with non-surgical emergencies, like an abnormal heart beat, and they’re triaged to decide the best route of care for them. In some cases that will be an admission to hospital, but increasingly this may involve alternatives that combine just a few hours in hospital with close follow up and perhaps even forms of remote monitoring, like monitoring their heart through a mobile app.

The aim of this project was to model part of the acute medical pathway in this hospital trust, simulate how the system currently works, and investigate whether there is optimal allocation of staff and resources. The benefit of this model is it allows for changing parameters such as adding extra staffing to see what impact that has on the pathway. Testing these changes in the real-world costs time and money, while computer simulation allows you to trial these changes with minimal cost and no risk.

The model isn’t validated yet, but when it is it’ll be handed over to users (e.g. clinicians and managers) to support them in making decisions about staffing or resourcing. They’ll be able to test those changes mentioned above without risk before proceeding to a real-world test of change.

{{< video https://www.youtube.com/watch?v=_3j0xC_yCKQ >}}

[Access the Github Repository](https://github.com/BeckyCrofts/amu_modelling)
